### ISSUE TITLE
React dependency need, after upgrade from 2.4.1 to 2.6.0

### ISSUE THREAD

**Issue by vsychov** [NerdWalletOSS/apollo-cache-policies#51]
Hello,

after upgrade from 2.4.1 to 2.6.0 on quasar based project, I'm getting error about missing `react` dependency:

```
 App •  ERROR  •  Client-side  in ./node_modules/@apollo/client/react/context/ApolloConsumer.js

Module not found: Can't resolve imported dependency "react"
Did you forget to install it? You can run: yarn add react

 App •  ERROR  •  Client-side  in ./node_modules/@apollo/client/react/hooks/useApolloClient.js

Module not found: Can't resolve imported dependency "react"
Did you forget to install it? You can run: yarn add react


 App •  COMPILATION FAILED  • Please check the log above for details.

error Command failed with exit code 1.
```

**Comment by danReynolds** [comment]
React isn't a dependency on the project, only a dev dependency. Does your project use react?

**Comment by vsychov** [comment]
My project don't use react, but looks like after update 2.4.1 to 2.6.0 apollo-cache-policies trying to call something from apollo, that needs react.

**Comment by LiamKarlMitchell** [comment]
Is there a way to get the ttl cache policies working without react I'm using Apollo Core (With Vue Apollo).
@vsychov did you find solution for this already?

**Comment by vsychov** [comment]
@LiamKarlMitchell , you can use 2.4.1 version, it's works well
